#!/usr/bin/env python
# coding: utf-8

# ## load packages

# In[30]:


import numpy as np
import glob
import pandas as pd


# ## load data using glob & read with pandas
# There are nested folders, so we will use 'recursive = True'

# In[130]:


files = glob.glob('/Users/cmbreen/Documents/Chapter 1/SnoqData/apu31/**/*.dat', recursive=True)  

data = []
for file in files: 
    datContent1 = [i.strip().split() for i in open(file, encoding='latin1').readlines()]
    data.append(datContent1)


# ## clean up dat files with func processDat()
# We only need the first 8 data points from each entry

# In[239]:


def processDat(data):
    Dates1 = []
    df1 = pd.DataFrame(columns = ['column0', 'column1', 'column2', 'column3', 'column4', 'column5', 'column6', 'column7', 'column8'])

    ## loop through every folder
    for i in range(0, len(data)):
        ## loop through every file
        for j in range(0, len(data[i])): 
            contents = data[i][j]
            data1 = contents[0]
            ## turn it into a table 
            fulldate = contents[0].split(";")[0]
            #dayHour = fulldate[]
            #print(date)
            if (fulldate[10:15] == '0100'): # or (fulldate[10:15] == '0000'):
                values1 = contents[0].split(";")[1].split(',')
                #print(values)

                df1.loc[len(df1.index)] = values1[0:9]
                Dates1.append(fulldate)
    return (Dates1, df1)


# ## Run function
# The outputs are a dates list and a list of values

# In[235]:


test1, test2 = processDat(data)
print(test2)


# ## clean up datetime list and add to dataframe

# In[238]:


def datetimeCleanup(Dates1, df1):
    YearMonDayList = []
    hourList = []
    for item in Dates1: 
        #YearMonDay = Dates1[1][0:8]
        #hour = Dates1[1][9:11]
        YearMonDay = item[0:8]
        hour = item[8:10]
        YearMonDayList.append(YearMonDay)
        hourList.append(hour)
    
    df1['Date'] = YearMonDayList
    df1['Hour'] = hourList
    df1['Dates'] = Dates1
    df1['Hour'] = df1['Hour'].astype(int)
    df1.sort_values(by = ['Date', 'Hour'], ascending = [True, True], na_position = 'first')
    
    return df1


# ## Run function

# In[240]:


df2 = datetimeCleanup(Dates1 = test1, df1 = test2)


# In[242]:


df2.to_csv('parsivelOutput_0100.csv')


# In[232]:


df1.to_csv('parsivelOutput.csv')


# In[ ]:




